services:
  mcp-server-as-http:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:3000
    environment:
      # Override default environment variables here
      - HTTP_API_KEY=${HTTP_API_KEY:-your-secret-api-key-here}
      - DISABLE_AUTH=${DISABLE_AUTH:-false}
      - MCP_CONFIG_FILE=mcp_servers.config.json
      - MCP_SERVER_NAME=${MCP_SERVER_NAME:-github}
      - RUST_LOG=${RUST_LOG:-info}
      - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_PERSONAL_ACCESS_TOKEN}
    volumes:
      # Mount config file for easy development changes
      - ./mcp_servers.config.json:/app/mcp_servers.config.json:ro
      # Optional: mount custom .env file
      - ./.env:/app/.env:ro
      # Mount Docker socket for Docker-in-Docker
      - /var/run/docker.sock:/var/run/docker.sock:rw
    user: root # Temporarily run as root to access docker socket
    restart: unless-stopped
